import { locateByAddress, shortStreet } from './grodno-geo.js';

export const ZAGOTTORG_PRICES =
  'Макулатура, стеклобой, полимеры, металлы, масла, бытовая техника, стеклотара. Актуальный прайс – на месте и на zagottorg.by';

const ZAGOTTORG_ACCEPTS = 'paper,electronics,metal';

function inferAccessMode(point) {
  if (point.access_mode) return point.access_mode;
  const blob = `${point.name} ${point.hours} ${point.description} ${point.logistics}`;
  if (/контейнер/i.test(blob)) return 'box';
  if (point.type === 'clothing') return 'desk';
  return 'counter';
}

function fillGeo(point) {
  const geo = locateByAddress(point.address) || locateByAddress(point.name);
  return {
    ...point,
    transit: point.transit || geo?.transit || '',
    district: point.district || geo?.district || 'Ленинский',
    lat: point.lat ?? geo?.lat ?? 53.6693,
    lng: point.lng ?? geo?.lng ?? 23.8131,
    short_address: point.short_address || shortStreet(point.address),
    accepts: point.accepts || point.type,
    last_synced: point.last_synced || null,
    oblast: point.oblast || 'Гродненская область',
    settlement: point.settlement || 'Гродно',
    access_mode: inferAccessMode(point),
  };
}

function zagottorg(sourceKey, name, address, hours, extra = {}) {
  return fillGeo({
    source_key: sourceKey,
    organization: 'Гродненский заготторг',
    name,
    type: 'paper',
    accepts: ZAGOTTORG_ACCEPTS,
    address,
    phone: '8 (0152) 66-04-31',
    website: 'https://zagottorg.by/adresa/',
    hours,
    prices: ZAGOTTORG_PRICES,
    logistics: 'Ларёк / пункт. За 15 минут до конца дня приём не ведётся. Во время отгрузки приём не производится. Вывоз: +375 (152) 66-39-55',
    description: 'Официальный пункт УП «Гродненский заготторг»: макулатура, стекло, полимеры, металлы, масла, бытовая техника, стеклотара.',
    ...extra,
  });
}

export const POINTS = [
  zagottorg(
    'zagottorg:победы-16',
    'Заготторг – пер. Победы, 16',
    'пер. Победы, 16',
    'Пн–Вс 08:30–17:00, обед 13:00–13:30. Работает в воскресенье.',
    { phone: '+375 (152) 66-39-55', logistics: 'Главный пункт. Самовывоз и заявки на вывоз: +375 (152) 66-39-55' },
  ),
  zagottorg('zagottorg:богуцкого', 'Заготторг – ул. Богуцкого', 'ул. Богуцкого (въезд в гаражный кооператив)', 'Пн: выходной | Вт–Сб 09:00–13:00 | Вс: выходной'),
  zagottorg('zagottorg:озерское-16е', 'Заготторг – Озёрское шоссе, 16Е', 'ул. Озерское шоссе, 16Е', 'Пн: выходной | Вт 10:00–15:00 | Ср–Сб 09:00–15:00 | Вс: выходной'),
  zagottorg('zagottorg:поповича-19', 'Заготторг – ул. Поповича', 'ул. Поповича (около д. 19)', 'Пн: выходной | Вт 11:00–14:00 | Ср–Пт 11:00–14:00 | Сб 10:00–14:00 | Вс: выходной'),
  zagottorg('zagottorg:пестрака', 'Заготторг – ул. Пестрака', 'ул. Пестрака (напротив гаражного кооператива)', 'Пн: выходной | Вт 12:00–16:00 | Ср–Сб 08:00–12:00 | Вс: выходной'),
  zagottorg('zagottorg:дзержинского-125', 'Заготторг – ул. Дзержинского', 'ул. Дзержинского (около д. 125)', 'Пн: выходной | Вт–Ср 09:00–13:00 | Чт–Пт 12:00–16:00 | Сб 09:00–13:00 | Вс: выходной'),
  zagottorg('zagottorg:скрынника-павлова', 'Заготторг – Скрынника / Павлова', 'пересечение ул. Ивана Скрынника и Павлова', 'Вт–Чт 10:00–14:00 | Пт 12:00–16:00 | Сб 10:00–14:00 | Пн, Вс: выходной'),
  zagottorg('zagottorg:купалы', 'Заготторг – ул. Янки Купалы', 'ул. Янки Купалы', 'Вт–Сб 14:00–15:00 | Пн, Вс: выходной'),
  zagottorg('zagottorg:мира-5', 'Заготторг – ул. Мира', 'ул. Мира (около д. 5)', 'Пн–Пт 08:00–12:00 | Сб–Вс: выходной'),
  zagottorg('zagottorg:сухомбаева', 'Заготторг – ул. Сухомбаева', 'ул. Сухомбаева (около СШ №16)', 'Временно не работает (официальный сайт)'),
  zagottorg('zagottorg:белые-росы', 'Заготторг – ул. Белые Росы', 'ул. Белые Росы (район автостоянки)', 'Пн: выходной | Вт–Пт 10:00–14:00 | Сб 09:00–13:00 | Вс: выходной'),
  zagottorg('zagottorg:терешковой-20б', 'Заготторг – ул. Терешковой', 'ул. Терешковой (около д. 20б)', 'Пн 09:00–13:00 | Вт 11:00–15:00 | Ср–Чт 09:00–13:00 | Пт 11:00–15:00 | Сб–Вс: выходной'),
  zagottorg('zagottorg:кабяка', 'Заготторг – ул. Кабяка', 'ул. Кабяка (около д. 10/2)', 'Пн–Пт 10:00–14:00 | Сб–Вс: выходной'),
  zagottorg('zagottorg:южная-9', 'Заготторг – ул. Южная', 'ул. Южная (около д. 9)', 'Пн: выходной | Вт 13:15–16:15 | Ср 13:30–15:30 | Чт 12:15–15:15 | Пт 13:30–15:30 | Сб 12:15–15:15 | Вс: выходной'),
  zagottorg('zagottorg:репина', 'Заготторг – ул. Репина', 'ул. Репина (около гаражей)', 'Пн: выходной | Вт 10:00–13:00 | Ср–Сб 09:00–12:00 | Вс: выходной'),
  zagottorg('zagottorg:волкова-41а', 'Заготторг – ул. Волкова', 'ул. Волкова, 41а (район гаражей)', 'Пн: выходной | Вт–Чт 09:30–13:30 | Пт 12:30–16:30 | Сб 09:00–13:00 | Вс: выходной'),
  zagottorg('zagottorg:зарица-2', 'Заготторг – Зарица-2', 'мкр. Зарица-2, ул. Зарицкая (у трансформаторного пункта)', 'Пн–Вт: выходной | Ср–Чт 13:00–17:00 | Пт–Вс 10:00–14:00'),
  zagottorg('zagottorg:барановичи', 'Заготторг – мкр. Барановичи', 'микрорайон Барановичи', 'Пн: выходной | Вт–Чт 14:30–17:30 | Пт–Сб 14:30–16:30 | Вс: выходной'),

  fillGeo({
    source_key: 'belvtor:хвойная-1',
    organization: 'БелВТИ (Белвторотходы)',
    name: 'БелВТИ – ул. Хвойная, 1',
    type: 'electronics',
    accepts: 'electronics,hazardous',
    address: 'ул. Хвойная, 1',
    phone: '+375 (152) 96-72-90, +375 (29) 709-77-05',
    website: 'https://belvtor.by/branchs/',
    hours: 'Пн–Пт 08:00–16:30, обед 12:30–13:00 | Сб–Вс: выходной',
    prices: 'Бытовая и оргтехника: от 0,30 BYN/кг. Аккумуляторы – по весу.',
    logistics: 'Самовывоз. Выездные бригады: Пн-Пт –, Сб –. Тел. 7705',
    description: 'Официальный филиал в Гродно. Переработка оргтехники, бытовой техники, электроники, аккумуляторов.',
  }),

  fillGeo({
    source_key: 'grodnobvm:скидельское-8в',
    organization: 'Гродновторчермет',
    name: 'Гродновторчермет – Скидельское шоссе, 8в',
    type: 'metal',
    address: 'ш. Скидельское, 8в',
    phone: '+375 (152) 68-16-85',
    website: 'https://grodnobvm.by/informacziya-dlya-fizicheskih-licz/',
    hours: 'Пн–Чт 07:30–16:22 | Пт 07:30–15:22 | обед 11:30–12:10 | Сб–Вс: выходной',
    prices: 'Чёрные и цветные металлы – по официальному прейскуранту на grodnobvm.by',
    logistics: 'Приём от физ. и юр. лиц, автомобильные весы. Вывоз: +375 (152) 68-16-83',
    description: 'Главный цех. Расчёт в день сдачи.',
  }),
  fillGeo({
    source_key: 'grodnobvm:ткацкая-8',
    organization: 'Гродновторчермет',
    name: 'Гродновторчермет – ул. Ткацкая, 8',
    type: 'metal',
    address: 'ул. Ткацкая, 8',
    phone: '+375 (152) 68-16-85',
    website: 'https://grodnobvm.by/informacziya-dlya-fizicheskih-licz/',
    hours: 'Пн, Вт, Ср, Пт 08:00–16:32 | Сб 08:00–15:32 | обед 12:00–12:20 | Чт, Вс: выходной',
    prices: 'Металлолом – по официальному прейскуранту',
    logistics: 'Приём от физических лиц',
    description: 'Стационарный пункт для населения.',
  }),
  fillGeo({
    source_key: 'grodnobvm:южный-30',
    organization: 'Гродновторчермет',
    name: 'Гродновторчермет – рынок «Южный»',
    type: 'metal',
    address: 'Индурское шоссе, 30 (рынок «Южный»)',
    phone: '+375 (152) 68-16-85',
    website: 'https://grodnobvm.by/informacziya-dlya-fizicheskih-licz/',
    hours: 'Вт 09:00–14:20 | Ср–Сб 09:00–18:05 | обед 11:30–12:00 | Вс, Пн: выходной',
    prices: 'Металлолом – по официальному прейскуранту',
    logistics: 'Приём от физических лиц',
    description: 'Пункт на рынке «Южный».',
  }),

  fillGeo({
    source_key: 'rpro:гаражная-6',
    organization: 'РесайклПро',
    name: 'РесайклПро – ул. Гаражная, 6',
    type: 'electronics',
    accepts: 'electronics,hazardous',
    address: 'ул. Гаражная, 6',
    phone: '+375 (29) 308-94-26',
    website: 'https://rpro.by/punkty-priema',
    hours: 'Будни и выходные – уточняйте на rpro.by (пункт в Гродно возобновил работу)',
    prices: 'Радиодетали, платы, катализаторы – по калькулятору на сайте',
    logistics: 'Скупка у населения. Для юрлиц – утилизация оборудования. Бывают выездные дни по Гродно.',
    description: 'Официальный пункт «РесайклПро» в Гродно.',
  }),

  fillGeo({
    source_key: '1ak:суворова-166',
    organization: '1AK',
    name: '1AK – ул. Суворова, 166',
    type: 'hazardous',
    address: 'ул. Суворова, 166',
    phone: '+375 (29) 345-59-00',
    website: 'https://1ak.by/tradein',
    hours: 'Пн–Пт 09:00–19:00 | Сб–Вс 09:00–18:00',
    prices: 'АКБ примерно 1,20 BYN/кг, расчёт на месте. Trade-in на новый аккумулятор.',
    logistics: 'Самовывоз. Взвешивание при вас.',
    description: 'Первая аккумуляторная компания. Приём любых АКБ.',
  }),
  fillGeo({
    source_key: '1ak:индурское-11',
    organization: '1AK',
    name: '1AK – Индурское шоссе, 11',
    type: 'hazardous',
    address: 'Индурское шоссе, 11',
    phone: '+375 (29) 345-59-00',
    website: 'https://1ak.by/tradein',
    hours: 'Пн–Пт 09:00–19:00 | Сб–Вс 09:00–18:00',
    prices: 'АКБ примерно 1,20 BYN/кг, расчёт на месте.',
    logistics: 'Самовывоз',
    description: 'Магазин и пункт приёма аккумуляторов.',
  }),
  fillGeo({
    source_key: '1ak:лиможа-54',
    organization: '1AK',
    name: '1AK – ул. Лиможа, 54',
    type: 'hazardous',
    address: 'ул. Лиможа, 54',
    phone: '+375 (29) 345-59-00',
    website: 'https://1ak.by/tradein',
    hours: 'Пн–Пт 09:00–19:00 | Сб–Вс 09:00–18:00',
    prices: 'АКБ примерно 1,20 BYN/кг, расчёт на месте.',
    logistics: 'Самовывоз',
    description: 'Магазин и пункт приёма аккумуляторов.',
  }),

  fillGeo({
    source_key: 'caritas:маркса-4',
    organization: 'Caritas',
    name: 'Caritas – ул. Карла Маркса, 4',
    type: 'clothing',
    address: 'ул. Карла Маркса, 4',
    phone: '+375 (152) 56-16-47, +375 (152) 55-46-68',
    website: 'https://www.caritas.by/ru/contacts',
    hours: 'Пн–Пт 10:00–16:00 (уточняйте перед визитом)',
    prices: 'Бесплатная сдача',
    logistics: 'Одежда, обувь, игрушки, книги – чистые, в хорошем состоянии. Звоните заранее.',
    description: 'Благотворительное общество «Caritas» Гродненской епархии.',
  }),
  fillGeo({
    source_key: 'redcross:карбышева-24',
    organization: 'Красный Крест',
    name: 'Красный Крест – контейнер на Карбышева, 24',
    type: 'clothing',
    address: 'ул. Карбышева, 24',
    phone: '+375 (152) 62-57-51',
    website: 'https://www.redcross.by/containers-for-collecting-clothes',
    hours: 'Контейнер: круглосуточно. Можно сдать и взять вещи.',
    prices: 'Бесплатная сдача',
    logistics: 'Только чистые вещи в надлежащем состоянии.',
    description: 'Городская организация Белорусского Красного Креста.',
  }),
  fillGeo({
    source_key: 'redcross:ожешко-1',
    organization: 'Красный Крест',
    name: 'Красный Крест – ул. Ожешко, 1',
    type: 'clothing',
    address: 'ул. Ожешко, 1',
    phone: '+375 (152) 68-00-00',
    website: 'https://www.redcross.by/grodno-obl-org',
    hours: 'Пн–Пт 09:00–17:00',
    prices: 'Бесплатная сдача',
    logistics: 'Одежда и обувь в хорошем состоянии. Звоните перед визитом.',
    description: 'Областная организация Красного Креста.',
  }),
  fillGeo({
    source_key: 'grbo:академическая-2',
    organization: 'GRBO',
    name: 'GRBO – пункт гуманитарной помощи',
    type: 'clothing',
    address: 'ул. Академическая, 2',
    phone: '8 (0152) 39-67-90, +375 (29) 587-30-45',
    website: 'https://grbo.by/punkt-gumanitarnoy-pomoschi',
    hours: 'Пн, Пт, Сб 11:00–17:00. Вт–Чт и Вс – выходной.',
    prices: 'Бесплатно: и приём, и выдача',
    logistics: 'Одежда, обувь, гигиена, книги, детские вещи. Не принимают грязное, лекарства, ношеное нижнее бельё.',
    description: 'Гродненское благотворительное общество. Социальный «магазин» для нуждающихся.',
  }),
  fillGeo({
    source_key: 'invalid:менделеева-34а',
    organization: 'Общество инвалидов',
    name: 'Общество инвалидов',
    type: 'clothing',
    address: 'ул. Менделеева, 34А',
    phone: '+375 (152) 62-02-68',
    website: 'https://beloi.by/grodnenskaya-oblastnaya-organizatsiya-oo-beloi/',
    hours: 'Пн–Пт 09:00–17:00 (уточняйте на месте)',
    prices: 'Бесплатная сдача',
    logistics: 'Одежда и бытовые предметы для людей с инвалидностью.',
    description: 'Городское общество инвалидов.',
  }),
  fillGeo({
    source_key: 'labirint:куйбышева-18',
    organization: 'Лабиринт добра',
    name: '«Лабиринт добра»',
    type: 'clothing',
    address: 'пер. Куйбышева, 18',
    phone: '',
    website: 'https://t.me/labirint_dobra',
    hours: 'По договорённости с волонтёрами',
    prices: 'Бесплатная сдача',
    logistics: 'Детские вещи. Напишите @labirint_dobra в Telegram.',
    description: 'Волонтёрский приём детских вещей.',
  }),
  fillGeo({
    source_key: 'heart:лапенковская-7',
    organization: 'Преданное сердце',
    name: 'ГООЗЖ «Преданное сердце»',
    type: 'clothing',
    address: 'ул. Лапенковская, 7',
    phone: '',
    website: 'https://predannoeserdce.by/kontakty',
    hours: 'Пн–Вс 10:00–18:00 (уточняйте)',
    prices: 'Бесплатная сдача',
    logistics: 'Старые вещи, ковры, линолеум – для домиков животных.',
    description: 'Помощь бездомным животным.',
  }),
  fillGeo({
    source_key: 'library:карского-29',
    organization: 'Библиотека им. Е.Ф. Карского',
    name: 'Библиотека им. Е.Ф. Карского',
    type: 'clothing',
    accepts: 'clothing',
    address: 'ул. Карбышева, 17',
    phone: '+375 (152) 71-89-53',
    website: 'https://grodnolib.by/',
    hours: 'Вт–Чт 10:00–19:00 | Сб–Вс 10:00–18:00 | Пт: выходной',
    prices: 'Безвозмездная передача книг',
    logistics: 'Книги в хорошем состоянии. Справочная: +375 (152) 71-89-53.',
    description: 'Областная научная библиотека им. Я.Ф. Карского принимает книги.',
  }),
  fillGeo({
    source_key: 'shelter:карского-29',
    organization: 'Дом ночного пребывания',
    name: 'Дом ночного пребывания',
    type: 'clothing',
    address: 'ул. Карского, 29',
    phone: '+375 (152) 61-08-31, +375 (152) 61-08-32',
    website: 'https://grodno.gov.by/',
    hours: 'Круглосуточно',
    prices: 'Бесплатная сдача одежды',
    logistics: 'Одежда для людей без определённого места жительства.',
    description: 'Городской дом ночного пребывания.',
  }),
  fillGeo({
    source_key: 'brigitki:маркса',
    organization: 'Бригитский монастырь',
    name: 'Женский бригитский монастырь',
    type: 'clothing',
    address: 'перекрёсток ул. К. Маркса и Молодёжной',
    phone: '8 (0152) 77-01-81',
    website: 'https://msj.by/katolicheskie-xramy/brigitskiy-kostel-v-grodno/',
    hours: 'Пн–Пт 09:00–16:00',
    prices: 'Бесплатная сдача',
    logistics: 'Одежда, обувь, предметы быта.',
    description: 'Приём вещей для нуждающихся.',
  }),
];

export const DATA_VERSION = 11;
